### ISSUE TITLE
Rubix installation fails on EMR Presto 0.194

### ISSUE THREAD

**Issue by vrajat** [qubole/rubix-admin#8]
@wishnick reported the following:

> In this attempt I tried to use the rubix admin utility. This did not work because it expects the plugin directory to
be /usr/lib/presto/plugin . (Later it was suggested to me in the presto slack group that I create a
symlink to this directory, but I had already moved on past this to attempt 3).

More information from the slack channel:

>so i did try to follow this instructions at one point and the install failed, partly because our presto plugin directory is different from the one that the admin tool expects. could that possibly be related to the version of presto we are using? i wasn't able to find any info on which version were compatible.

As part of announcing rubix-admin and rubix support for EMR, we had tested on 0.184. Current version is 0.194 and the paths may have changed. 

There are two action items:
- Test again on latest EMR (and probably setup a regression framework)
- Make the directories pluggable so that there is an escape valve if installation config changes.

cc @abhishekdas99

**Comment by kushagro123** [comment]
@vrajat Could you please share the exception that appears? We ran rubix admin with the default plugin directory /usr/lib/presto/plugin/hive-hadoop2/ and it worked fine with version 0.194.

**Comment by vrajat** [comment]
This was reported by @wishnick. I am not sure if he has the exception anymore. If you are not able to reproduce it. Please go ahead and close the issue.

**Comment by abhishekdas99** [comment]
We are able to install RubiX in EMR Presto .194
